// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ThemeToggler
{
    internal sealed partial class Vsix
    {
        public const string Id = "d594855a-8bf8-4910-bf4f-5ce4734ee604";
        public const string Name = "ThemeToggler";
        public const string Description = @"Adds a Togglebutton to switch between those sweet 'n juicy themes";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Redmer Nauta";
        public const string Tags = "";
    }
}
