// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ThemeToggler
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ThemeTogglerString = "8bfcc1ec-e93b-4780-862f-800dd53ca38b";
        public static Guid ThemeToggler = new Guid(ThemeTogglerString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ThemeTogglerListGroup = 0x0012;
        public const int ThemeTogglerMenu = 0x0013;
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
        public const int Toolbar = 0x1001;
        public const int ToolbarGroup = 0x1050;
        public const int FirstTheme = 0x0101;
    }
}